// Generated by CoffeeScript 1.7.1
(function() {
  var changeSliderColor, createElement, deletePage, loadEditor, monitorStatus, restorePage, scrollToPage, scrollerCurrentPage, scrollerMaxPage, scrollerMinPage, sendEvent, sendPageView, setupAnalytics, setupButtons, setupContactForm, setupHashes, setupScroller, siteOnline, typeBuffer, typeCode, typeLine;

  $(function() {
    console.log("gavyaggarwal.com Loaded");
    loadEditor();
    setupButtons();
    setupScroller();
    setupContactForm();
    setupHashes();
    setupAnalytics();
    return monitorStatus();
  });

  loadEditor = function() {
    var request1, request2;
    request1 = $.ajax("Source/index.jade");
    request1.done(function() {
      return typeCode(request1.responseText, "#pane1");
    });
    request2 = $.ajax("Source/style.less");
    return request2.done(function() {
      return typeCode(request2.responseText, "#pane2");
    });
  };

  typeCode = function(code, pane) {
    var finished, lines;
    lines = code.split("\n");
    finished = function() {
      console.log("Finished Typing Code (" + pane + ")");
      return sendEvent('editor', 'finished typing', pane);
    };
    return typeLine(lines, finished, pane, 0);
  };

  typeLine = function(code, callback, pane, line) {
    var finishedLine, text;
    if (line === code.length) {
      return callback();
    } else {
      text = code[line];
      finishedLine = function() {
        $(pane).append('<br />');
        return typeLine(code, callback, pane, line + 1);
      };
      return typeBuffer(text, finishedLine, pane, 0);
    }
  };

  typeBuffer = function(buffer, callback, pane, index, isSecondWord, inBrackets, inQuotes, hadFirstSpace) {
    var char, color, element, timerDone;
    if (index === buffer.length) {
      return callback();
    } else {
      char = buffer.charAt(index);
      if (!hadFirstSpace) {
        if (char !== " ") {
          hadFirstSpace = true;
        }
      } else {
        if (char === " ") {
          isSecondWord = true;
        }
      }
      if (inBrackets) {
        inBrackets = !(char === ")");
      } else {
        inBrackets = char === "(";
      }
      if (char === "'") {
        inQuotes = !inQuotes;
      }
      if (!hadFirstSpace) {
        char = "&emsp;&emsp;";
      }
      color = isSecondWord ? "#DBDDDE" : "#FFCD02";
      if (inBrackets) {
        color = "#34AADC";
      }
      if (inQuotes) {
        color = "#FF3B30";
      }
      if ((char === "(") || (char === ")") || (char === "=") || (char === ",")) {
        color = "#DBDDDE";
      }
      if (char === "'") {
        color = "#FF3B30";
      }
      element = createElement(char, color);
      $(pane).append(element);
      timerDone = function() {
        return typeBuffer(buffer, callback, pane, index + 1, isSecondWord, inBrackets, inQuotes, hadFirstSpace);
      };
      return setTimeout(timerDone, 100);
    }
  };

  createElement = function(char, color) {
    var span;
    return span = '<span style="color: ' + color + ';">' + char + '</span>';
  };

  setupButtons = function() {
    $("#down-button").click(function() {
      sendEvent('navigation', 'click', 'down button');
      $('html,body').animate({
        scrollTop: $("#panel2").offset().top
      }, 1000);
      return false;
    });
    return $("#up-button").click(function() {
      sendEvent('navigation', 'click', 'up button');
      $('html,body').animate({
        scrollTop: 0
      }, 1000);
      return false;
    });
  };

  scrollerCurrentPage = 0;

  scrollerMinPage = 0;

  scrollerMaxPage = 0;

  setupScroller = function() {
    var dot, dots, i, length, selectedClass, _i;
    length = $(".slider-content").length;
    scrollerCurrentPage = 0;
    scrollerMinPage = 0;
    scrollerMaxPage = length - 1;
    dots = $("#dots");
    for (i = _i = 0; 0 <= length ? _i < length : _i > length; i = 0 <= length ? ++_i : --_i) {
      selectedClass = i === 0 ? " selected" : "";
      dot = '<div class="dot' + selectedClass + '"></div>';
      $(dots).append(dot);
    }
    $("#left").click(function() {
      scrollerCurrentPage--;
      return scrollToPage();
    });
    $("#right").click(function() {
      scrollerCurrentPage++;
      return scrollToPage();
    });
    $(".dot").click(function() {
      scrollerCurrentPage = $(this).index();
      return scrollToPage();
    });
    return scrollToPage();
  };

  scrollToPage = function() {
    var content, dots, offsetLeft;
    $("#left").css({
      opacity: scrollerCurrentPage <= scrollerMinPage ? 0 : ''
    });
    $("#right").css({
      opacity: scrollerCurrentPage >= scrollerMaxPage ? 0 : ''
    });
    if (scrollerCurrentPage < scrollerMinPage) {
      scrollerCurrentPage = scrollerMinPage;
    }
    if (scrollerCurrentPage > scrollerMaxPage) {
      scrollerCurrentPage = scrollerMaxPage;
    }
    offsetLeft = $($('.slider-content')[scrollerCurrentPage]).offset().left;
    $('#viewport').animate({
      scrollLeft: '+=' + offsetLeft
    }, 1000);
    dots = $(".dot");
    $(dots).removeClass("selected");
    $(dots[scrollerCurrentPage]).addClass("selected");
    changeSliderColor();
    content = $($('.slider-content')[scrollerCurrentPage]).attr('id');
    return sendEvent('projects', 'loaded', content);
  };

  changeSliderColor = function() {
    var arrows, color, content, dots, panel, slider;
    panel = $('#panel2');
    slider = panel.find('#slider');
    content = slider.find('.slider-content')[scrollerCurrentPage];
    arrows = slider.find('#left,#right');
    dots = slider.find('.dot');
    color = $(content).css('color');
    panel.css({
      color: color,
      borderTopColor: color,
      borderBottomColor: color
    });
    arrows.css({
      background: color
    });
    return dots.css({
      backgroundColor: color
    });
  };

  setupContactForm = function() {
    $("#contactmessage").keyup(function() {
      this.style.height = '1px';
      return this.style.height = (40 + this.scrollHeight) + 'px';
    });
    return $("#submitform").click(function() {
      var email, form, formData, formError, formSubmitted, formSuccess, message, name, span, status, subject;
      form = $("form");
      name = $(form).find("input[name=name]").val();
      email = $(form).find("input[name=email]").val();
      subject = $(form).find("input[name=subject]").val();
      message = $(form).find("input[name=message]").val();
      if (name === "" || email === "" || subject === "" || message === "") {
        console.log("Invalid Form Data");
        span = $(this).find("span");
        $(span).transition({
          x: '20px'
        }, 70, 'ease');
        $(span).transition({
          x: '-20px'
        }, 140, 'ease');
        $(span).transition({
          x: '20px'
        }, 140, 'ease');
        $(span).transition({
          x: '-20px'
        }, 140, 'ease');
        $(span).transition({
          x: '0px'
        }, 70, 'ease');
        return sendEvent('contact', 'submit', 'invalid data');
      } else {
        formData = $(form).serialize();
        status = $("#contactstatus");
        formError = function() {
          $(status).html("Something went wrong! Just shoot me an <a href='mailto:gavyaggarwal@gmail.com'>email</a> instead.");
          $(status).css({
            opacity: 1
          });
          console.log("Error Submitting Contact Form");
          return sendEvent('contact', 'submit', 'error');
        };
        formSuccess = function() {
          $(status).html("Thanks for getting in touch. I'll get back to you soon!");
          $(status).css({
            opacity: 1
          });
          $(form).find("input[type=text], textarea").val("");
          console.log("Contact Form Submitted Successfully");
          return sendEvent('contact', 'submit', 'success');
        };
        formSubmitted = function() {
          $(status).html("Loading");
          return $(status).css({
            opacity: 1
          });
        };
        $.ajax({
          url: "http://bin.gavyaggarwal.com/mailer?" + formData,
          success: function(data) {
            if (data === "success") {
              return formSuccess();
            } else {
              return formError();
            }
          },
          error: function() {
            return formError();
          }
        });
        sendEvent('contact', 'submit', 'sending request to bin');
        return formSubmitted();
      }
    });
  };

  setupHashes = function() {
    var onScroll;
    onScroll = function() {
      return $('.anchor').each(function() {
        var elemHeight, elemTop, initialHash, winTop;
        elemTop = $(this).offset().top;
        elemHeight = $(this).parent().height();
        winTop = window.pageYOffset;
        if (elemTop < winTop + 10 && (elemTop + elemHeight) > winTop + 10) {
          initialHash = window.location.hash;
          window.location.hash = '#' + $(this).attr('id');
          $(document).scrollTop(winTop);
          if (window.location.hash !== initialHash) {
            return console.log("Page Changed to " + window.location.hash);
          }
        }
      });
    };
    return $(document).bind('scroll', onScroll);
  };

  setupAnalytics = function() {
    var fields, headings, isDev, links, trackingID;
    (function(i, s, o, g, r, a, m) {
      i["GoogleAnalyticsObject"] = r;
      i[r] = i[r] || function() {
        (i[r].q = i[r].q || []).push(arguments);
      };
      i[r].l = 1 * new Date();
      a = s.createElement(o);
      m = s.getElementsByTagName(o)[0];
      a.async = 1;
      a.src = g;
      m.parentNode.insertBefore(a, m);
    })(window, document, "script", "//www.google-analytics.com/analytics.js", "ga");
    isDev = !~window.location.href.indexOf('www');
    if (isDev) {
      console.log('Development Version');
    } else {
      console.log('Production Version');
    }
    trackingID = isDev ? 'UA-54102576-1' : 'UA-54102576-2';
    ga('create', trackingID, {
      alwaysSendReferrer: true
    });
    ga('require', 'displayfeatures');
    ga('require', 'linkid');
    ga('send', 'pageview');
    headings = $('#panel1 #items h3');
    headings.mouseover(function() {
      var text;
      text = $(this).html();
      return sendEvent('headers', 'hover', text);
    });
    fields = $('#panel4 form input,textarea');
    fields.focus(function() {
      var text;
      text = $(this).attr('placeholder');
      return sendEvent('contact', 'focus', text);
    });
    links = $('#panel4 .box');
    return links.click(function() {
      var text;
      text = $(this).find('span').html();
      return sendEvent('social links', 'click', text);
    });
  };

  sendPageView = function(page) {
    return ga('send', 'pageview', {
      'page': page
    });
  };

  sendEvent = function(category, action, label, value) {
    return ga('send', 'event', category, action, label, value);
  };

  siteOnline = true;

  monitorStatus = function() {
    var authenticate, callback;
    callback = function(status) {
      if (status.valueOf() === 'offline'.valueOf()) {
        if (siteOnline) {
          return deletePage();
        }
      } else {
        if (!siteOnline) {
          return restorePage();
        }
      }
    };
    authenticate = function() {
      return $.get('http://bin.gavyaggarwal.com/gavyaggarwal-status', callback);
    };
    authenticate();
    return setInterval(authenticate, 3000);
  };

  deletePage = function() {
    var container;
    siteOnline = false;
    console.log('Bye Guys! This site is going down!');
    container = $('#panel1 #content');
    container.empty();
    container.html('<h4>This website is temporarily unavailable.</h4> <h4>Please try again in a bit.</h4>');
    $('#background').empty();
    $('#panel2').remove();
    $('#panel3').remove();
    $('#panel4').remove();
    $('#panel5').remove();
    return sendEvent('page status', 'disabled');
  };

  restorePage = function() {
    var callback;
    siteOnline = true;
    callback = function() {
      console.log('Annnd, we\'re back up!');
      return location.reload();
    };
    return ga('send', {
      'hitCallback': callback,
      'hitType': 'event',
      'eventCategory': 'page status',
      'eventAction': 'enabled'
    });
  };

}).call(this);
