// Generated by CoffeeScript 1.7.1
(function() {
  var createElement, loadEditor, scrollToPage, scrollerCurrentPage, scrollerMaxPage, scrollerMinPage, setupButtons, setupContactForm, setupHashes, setupScroller, typeBuffer, typeCode, typeLine;

  $(function() {
    console.log("gavyaggarwal.com Loaded");
    loadEditor();
    setupButtons();
    setupScroller();
    setupContactForm();
    return setupHashes();
  });

  loadEditor = function() {
    var request1, request2;
    request1 = $.ajax("index.jade");
    request1.done(function() {
      return typeCode(request1.responseText, "#pane1");
    });
    request2 = $.ajax("style.less");
    return request2.done(function() {
      return typeCode(request2.responseText, "#pane2");
    });
  };

  typeCode = function(code, pane) {
    var finished, lines;
    lines = code.split("\n");
    finished = function() {
      return console.log("Finished Typing Code");
    };
    return typeLine(lines, finished, pane, 0);
  };

  typeLine = function(code, callback, pane, line) {
    var finishedLine, text;
    if (line === code.length) {
      return callback();
    } else {
      text = code[line];
      finishedLine = function() {
        $(pane).append('<br />');
        return typeLine(code, callback, pane, line + 1);
      };
      return typeBuffer(text, finishedLine, pane, 0);
    }
  };

  typeBuffer = function(buffer, callback, pane, index, isSecondWord, inBrackets, inQuotes, hadFirstSpace) {
    var char, color, element, timerDone;
    if (index === buffer.length) {
      return callback();
    } else {
      char = buffer.charAt(index);
      if (!hadFirstSpace) {
        if (char !== " ") {
          hadFirstSpace = true;
        }
      } else {
        if (char === " ") {
          isSecondWord = true;
        }
      }
      if (inBrackets) {
        inBrackets = !(char === ")");
      } else {
        inBrackets = char === "(";
      }
      if (char === "'") {
        inQuotes = !inQuotes;
      }
      if (!hadFirstSpace) {
        char = "&emsp;&emsp;";
      }
      color = isSecondWord ? "#DBDDDE" : "#FFCD02";
      if (inBrackets) {
        color = "#34AADC";
      }
      if (inQuotes) {
        color = "#FF3B30";
      }
      if ((char === "(") || (char === ")") || (char === "=") || (char === ",")) {
        color = "#DBDDDE";
      }
      if (char === "'") {
        color = "#FF3B30";
      }
      element = createElement(char, color);
      $(pane).append(element);
      timerDone = function() {
        return typeBuffer(buffer, callback, pane, index + 1, isSecondWord, inBrackets, inQuotes, hadFirstSpace);
      };
      return setTimeout(timerDone, 100);
    }
  };

  createElement = function(char, color) {
    var span;
    return span = '<span style="color: ' + color + ';">' + char + '</span>';
  };

  setupButtons = function() {
    $("#down-button").click(function() {
      return $('html,body').animate({
        scrollTop: $("#panel2").offset().top
      }, 1000);
    });
    return $("#up-button").click(function() {
      return $('html,body').animate({
        scrollTop: 0
      }, 1000);
    });
  };

  scrollerCurrentPage = 0;

  scrollerMinPage = 0;

  scrollerMaxPage = 0;

  setupScroller = function() {
    var dot, dots, i, length, selectedClass, _i;
    length = $(".slider-content").length;
    scrollerCurrentPage = 0;
    scrollerMinPage = 0;
    scrollerMaxPage = length - 1;
    dots = $("#dots");
    for (i = _i = 0; 0 <= length ? _i < length : _i > length; i = 0 <= length ? ++_i : --_i) {
      selectedClass = i === 0 ? " selected" : "";
      dot = '<div class="dot' + selectedClass + '"></div>';
      $(dots).append(dot);
    }
    $("#left").click(function() {
      scrollerCurrentPage--;
      return scrollToPage();
    });
    $("#right").click(function() {
      scrollerCurrentPage++;
      return scrollToPage();
    });
    $(".dot").click(function() {
      scrollerCurrentPage = $(this).index();
      return scrollToPage();
    });
    return scrollToPage();
  };

  scrollToPage = function() {
    var dots, offsetLeft;
    $("#left").css({
      opacity: scrollerCurrentPage <= scrollerMinPage ? 0 : ''
    });
    $("#right").css({
      opacity: scrollerCurrentPage >= scrollerMaxPage ? 0 : ''
    });
    if (scrollerCurrentPage < scrollerMinPage) {
      scrollerCurrentPage = scrollerMinPage;
    }
    if (scrollerCurrentPage > scrollerMaxPage) {
      scrollerCurrentPage = scrollerMaxPage;
    }
    offsetLeft = $($('.slider-content')[scrollerCurrentPage]).offset().left;
    $('#viewport').animate({
      scrollLeft: '+=' + offsetLeft
    }, 1000);
    dots = $(".dot");
    $(dots).removeClass("selected");
    return $(dots[scrollerCurrentPage]).addClass("selected");
  };

  setupContactForm = function() {
    $("#contactmessage").keyup(function() {
      this.style.height = '1px';
      return this.style.height = (40 + this.scrollHeight) + 'px';
    });
    return $("#submitform").click(function() {
      var email, form, formData, formError, formSubmitted, formSuccess, message, name, span, status, subject;
      form = $("form");
      name = $(form).find("input[name=name]").val();
      email = $(form).find("input[name=email]").val();
      subject = $(form).find("input[name=subject]").val();
      message = $(form).find("input[name=message]").val();
      if (name === "" || email === "" || subject === "" || message === "") {
        console.log("Invalid Form Data");
        span = $(this).find("span");
        $(span).transition({
          x: '20px'
        }, 70, 'ease');
        $(span).transition({
          x: '-20px'
        }, 140, 'ease');
        $(span).transition({
          x: '20px'
        }, 140, 'ease');
        $(span).transition({
          x: '-20px'
        }, 140, 'ease');
        return $(span).transition({
          x: '0px'
        }, 70, 'ease');
      } else {
        formData = $(form).serialize();
        status = $("#contactstatus");
        formError = function() {
          $(status).html("Something went wrong! Just shoot me an <a href='mailto:gavyaggarwal@gmail.com'>email</a> instead.");
          $(status).css({
            opacity: 1
          });
          return console.log("Error Submitting Contact Form");
        };
        formSuccess = function() {
          $(status).html("Thanks for getting in touch. I'll get back to you soon!");
          $(status).css({
            opacity: 1
          });
          $(form).find("input[type=text], textarea").val("");
          return console.log("Contact Form Submitted Successfully");
        };
        formSubmitted = function() {
          $(status).html("Loading");
          return $(status).css({
            opacity: 1
          });
        };
        $.ajax({
          url: "http://bin.gavyaggarwal.com/mailer?" + formData,
          success: function(data) {
            if (data === "success") {
              return formSuccess();
            } else {
              return formError();
            }
          },
          error: function() {
            return formError();
          }
        });
        return formSubmitted();
      }
    });
  };

  setupHashes = function() {
    var onScroll;
    onScroll = function() {
      return $('.anchor').each(function() {
        var elemHeight, elemTop, winTop;
        elemTop = $(this).offset().top;
        elemHeight = $(this).parent().height();
        winTop = window.pageYOffset;
        if (elemTop < winTop + 10 && (elemTop + elemHeight) > winTop + 10) {
          window.location.hash = $(this).attr('id');
          return $(document).scrollTop(winTop);
        }
      });
    };
    return $(document).bind('scroll', onScroll);
  };

}).call(this);
